config/routes.rb
Rails.application.routes.draw do

  # Citizens shouldn't be removed from db, only filtered in UI
  resources :municipes, except: :destroy

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  has_one_attached :foto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update ]

  # GET /municipes or /municipes.json
  def index
    @municipes = Municipe.all
  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully created." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe was successfully updated." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      params.require(:municipe).permit(:nome_completo, :cpf, :cns, :email, :data_nascimento, :telefone, :foto, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contactz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/municipes/_form.html.haml
= form_for @municipe do |f|
  - if @municipe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@municipe.errors.count, "error")} prohibited this municipe from being saved:"
      %ul
        - @municipe.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome_completo
    = f.text_field :nome_completo
  .field
    = f.label :cpf
    = f.text_field :cpf
  .field
    = f.label :cns
    = f.text_field :cns
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :data_nascimento
    = f.date_field :data_nascimento
  .field
    = f.label :telefone
    = f.text_field :telefone
  .field
    = f.label :foto
    = f.file_field :foto
  .field
    = f.label :status
    = f.check_box :status
  .actions
    = f.submit 'Save'

app/views/municipes/edit.html.haml
%h1 Editing municipe

= render 'form'

= link_to 'Show', @municipe
\|
= link_to 'Back', municipes_path

app/views/municipes/index.html.haml
%h1 Listing municipes

%table
  %thead
    %tr
      %th Nome completo
      %th Cpf
      %th Cns
      %th Email
      %th Data nascimento
      %th Telefone
      %th Foto
      %th Status
      %th
      %th
      %th

  %tbody
    - @municipes.each do |municipe|
      %tr
        %td= municipe.nome_completo
        %td= municipe.cpf
        %td= municipe.cns
        %td= municipe.email
        %td= municipe.data_nascimento
        %td= municipe.telefone
        %td= municipe.foto
        %td= municipe.status
        %td= link_to 'Show', municipe
        %td= link_to 'Edit', edit_municipe_path(municipe)
        %td= link_to 'Destroy', municipe, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Municipe', new_municipe_path

app/views/municipes/new.html.haml
%h1 New municipe

= render 'form'

= link_to 'Back', municipes_path

app/views/municipes/show.html.haml
%p#notice= notice

%p
  %b Nome completo:
  = @municipe.nome_completo
%p
  %b Cpf:
  = @municipe.cpf
%p
  %b Cns:
  = @municipe.cns
%p
  %b Email:
  = @municipe.email
%p
  %b Data nascimento:
  = @municipe.data_nascimento
%p
  %b Telefone:
  = @municipe.telefone
%p
  %b Foto:
  = @municipe.foto
%p
  %b Status:
  = @municipe.status

= link_to 'Edit', edit_municipe_path(@municipe)
\|
= link_to 'Back', municipes_path